### ISSUE TITLE
AttributeError: module 'cv2.detail' has no attribute 'WAVE_CORRECT_AUTO'

### ISSUE THREAD

**Issue by ma-xq** [lukasalexanderweber/stitching#22]
I installed it by pip,but it showed me AttributeError: module 'cv2.detail' has no attribute 'WAVE_CORRECT_AUTO'.What should I do?
C:\Users\Administrator>pip install stitching
Requirement already satisfied: stitching in d:\python\anaconda3\lib\site-package
s (0.3.0)
Requirement already satisfied: largestinteriorrectangle in d:\python\anaconda3\l
ib\site-packages (from stitching) (0.1.1)
Requirement already satisfied: opencv-python>=4.0.1 in d:\python\anaconda3\lib\s
ite-packages (from stitching) (4.2.0.34)
Requirement already satisfied: numpy>=1.14.5 in d:\python\anaconda3\lib\site-pac
kages (from opencv-python>=4.0.1->stitching) (1.21.6)
Requirement already satisfied: numba in d:\python\anaconda3\lib\site-packages (f
rom largestinteriorrectangle->stitching) (0.41.0)
Requirement already satisfied: llvmlite>=0.26.0dev0 in d:\python\anaconda3\lib\s
ite-packages (from numba->largestinteriorrectangle->stitching) (0.26.0)

**Comment by lukasalexanderweber** [comment]
your opencv version seems pretty old (4.2.0). Please consider upgrading and let me know if it worked

**Comment by lukasalexanderweber** [comment]
Try also upgrading numba

**Comment by ma-xq** [comment]
> Try also upgrading numba

After installing llvmlite-0.39.0 numba-0.56.0,new error occurred as below.
File "D:\Python\Anaconda3\lib\site-packages\numba\core\entrypoints.py", line 48, in init_all
    eps = importlib_metadata.entry_points()
TypeError: entry_points() missing 1 required positional argument: 'name'

**Comment by lukasalexanderweber** [comment]
are you on windows 11? maybe related to https://github.com/lukasalexanderweber/stitching_tutorial/issues/11

**Comment by ma-xq** [comment]
> are you on windows 11? maybe related to [lukasalexanderweber/stitching_tutorial#11](https://github.com/lukasalexanderweber/stitching_tutorial/issues/11)
No, I'm on windows 7, python 3.7.1. I think there may be some environment errors in numba, because different version of numba brings different errors after I tried numba-0.41.0, 0.56.0, 0.55.0, 0.50.0. Thank you very much for solving my problem.

**Comment by lukasalexanderweber** [comment]
have you found a sollution?

**Comment by ma-xq** [comment]
No.

**Comment by lukasalexanderweber** [comment]
so you are using anaconda.

You could try setting up a new virtual environment and install stitching there:

```
# Open Anaconda Prompt (base):
# Create new environment with Python 3.8:
conda create -n stitching python=3.8
# Activate your new Python 3.8 environment:
conda activate stitching
```

Check if stitching is available via conda: 
`conda search stitching
`
if yes, install
`conda install stitching
`
if not, do it via pypi
`pip install stitching`

**Comment by ma-xq** [comment]
It didn't work.Error information is:
`Command-line error: too many arguments on command line

1 catastrophic error detected in the compilation of "0)PROCESS(0".
Compilation terminated.
OpenCL program build log: imgproc/morph
Status -11: CL_BUILD_PROGRAM_FAILURE
-D RADIUSX=1 -D RADIUSY=1 -D LSIZE0=16 -D LSIZE1=16 -D OP_DILATE -D PROCESS_ELEMS=PROCESS(0,0)PROCESS(0,1)PROCESS(0,2)PROCESS(1,0)PROCESS(1,1)PROCESS(1,2)PROCESS(2,0)PROCESS(2,1)PROCESS(2,2) -D T=uchar -D DEPTH_0 -D cn=1 -D T1=uchar -D convertToWT=convert_float -D convertToT=convert_uchar_sat_rte -D ST=uchar -D AMD_DEVICE
Frontend phase failed compilation.
`

**Comment by lukasalexanderweber** [comment]
on which call does the error happen?

**Comment by ma-xq** [comment]
line:panorama = stitcher.stitch(["1.png", "2.png"])
`import stitching

print(stitching.__version__)  # ok
stitcher = stitching.Stitcher()  # ok
panorama = stitcher.stitch(["1.png", "2.png"])  # error`

**Comment by lukasalexanderweber** [comment]
ok so the installation worked apperently..

Maybe it's a numba issue, try with 

`stitcher = stitching.Stitcher(crop=False) `

**Comment by ma-xq** [comment]
> It didn't work.Error information is: `Command-line error: too many arguments on command line
> 
> 1 catastrophic error detected in the compilation of "0)PROCESS(0". Compilation terminated. OpenCL program build log: imgproc/morph Status -11: CL_BUILD_PROGRAM_FAILURE -D RADIUSX=1 -D RADIUSY=1 -D LSIZE0=16 -D LSIZE1=16 -D OP_DILATE -D PROCESS_ELEMS=PROCESS(0,0)PROCESS(0,1)PROCESS(0,2)PROCESS(1,0)PROCESS(1,1)PROCESS(1,2)PROCESS(2,0)PROCESS(2,1)PROCESS(2,2) -D T=uchar -D DEPTH_0 -D cn=1 -D T1=uchar -D convertToWT=convert_float -D convertToT=convert_uchar_sat_rte -D ST=uchar -D AMD_DEVICE Frontend phase failed compilation. `

same error

**Comment by lukasalexanderweber** [comment]
please share the EXACT steps what you are doing.

**Comment by ma-xq** [comment]
I'm so sorry that I made a mistake. I didn't notice that PyCharm 2018.3.5(I'm using) doesn't support  Python 3.8.
1.I create virtual conduct environment as you teach me.
2.Open pycharm and change it's project interpreter to the upper environment.In this step, the IDE show python=3.7.
3.In my script,run
```
import stitching

print(stitching.__version__)  # ok

stitcher = stitching.Stitcher(crop=False)  # ok
panorama = stitcher.stitch(["1.png", "2.png"])  # error
```
The IDE showed the error:

> It didn't work.Error information is: `Command-line error: too many arguments on command line
> 
> 1 catastrophic error detected in the compilation of "0)PROCESS(0". Compilation terminated. OpenCL program build log: imgproc/morph Status -11: CL_BUILD_PROGRAM_FAILURE -D RADIUSX=1 -D RADIUSY=1 -D LSIZE0=16 -D LSIZE1=16 -D OP_DILATE -D PROCESS_ELEMS=PROCESS(0,0)PROCESS(0,1)PROCESS(0,2)PROCESS(1,0)PROCESS(1,1)PROCESS(1,2)PROCESS(2,0)PROCESS(2,1)PROCESS(2,2) -D T=uchar -D DEPTH_0 -D cn=1 -D T1=uchar -D convertToWT=convert_float -D convertToT=convert_uchar_sat_rte -D ST=uchar -D AMD_DEVICE Frontend phase failed compilation. `

Then I tried on cmd.
1.Acitvate stitching environment.
2.Run `stitch 1.png 2.png`
It shows:
```
stitching 1.png 2.png into result.jpg
Command-line error: too many arguments on command line

1 catastrophic error detected in the compilation of "0)PROCESS(0".
Compilation terminated.
OpenCL program build log: imgproc/morph
Status -11: CL_BUILD_PROGRAM_FAILURE
-D RADIUSX=1 -D RADIUSY=1 -D LSIZE0=16 -D LSIZE1=16 -D OP_DILATE -D PROCESS_ELEM
S=PROCESS(0,0)PROCESS(0,1)PROCESS(0,2)PROCESS(1,0)PROCESS(1,1)PROCESS(1,2)PROCES
S(2,0)PROCESS(2,1)PROCESS(2,2) -D T=uchar -D DEPTH_0 -D cn=1 -D T1=uchar -D conv
ertToWT=convert_float -D convertToT=convert_uchar_sat_rte -D ST=uchar -D AMD_DEV
ICE
Frontend phase failed compilation.
```
I see the result.jpg although still have same error information.
Thank you very much.

**Comment by lukasalexanderweber** [comment]
> I see the result.jpg

Is this fine for you?

**Comment by ma-xq** [comment]
Yeah! It's so good! Thank you for your work.
