### ISSUE TITLE
how i can use it for microscope stiching

### ISSUE THREAD

**Issue by kuldeep203** [lukasalexanderweber/stitching#36]

**Comment by lukasalexanderweber** [comment]
do you have sample images?

**Comment by kuldeep203** [comment]
yes i have microscope images of blood smear slide.

**Comment by lukasalexanderweber** [comment]
have you tried stitching them? have you found problems? if yes, could you provide some sample images?

**Comment by kuldeep203** [comment]
i tried but i got the error below 
raise StitchingError("No match exceeds the " "given confidence threshold.")
stitching.stitching_error.StitchingError: No match exceeds the given confidence threshold.

**Comment by lukasalexanderweber** [comment]
you need to work with the settings:

see eg. https://github.com/lukasalexanderweber/stitching/issues/30#issuecomment-1285783813 -> you can lower the confidence threshold.

**Comment by kuldeep203** [comment]
now i set DEFAULT_CONFIDENCE_THRESHOLD = 0.2 but still not able to stich the images.

**Comment by kuldeep203** [comment]
This is my drive link of the 3 images.
https://drive.google.com/drive/folders/1cmhZT75T7C8w-4V0riBP9xBIR-vVyRzq

**Comment by kuldeep203** [comment]
please help me its very crucial for me to stitch microscope image.

**Comment by lukasalexanderweber** [comment]
you need to give access to the images, I just requested it

**Comment by kuldeep203** [comment]
i had and i have mailed one complete image zip file also.

**Comment by lukasalexanderweber** [comment]
I don't see an overlap between the images

**Comment by kuldeep203** [comment]
There is hundreds percent overlap.or you can use the folder and can choose
any regular images for stitching.

kuldeep

**Comment by lukasalexanderweber** [comment]
What?

**Comment by kuldeep203** [comment]
i have share you one image folder in mail attachment. so please let me know if you can stitch any of two images.

**Comment by lukasalexanderweber** [comment]
I've had another look at it but it can't find good matches, even if there is overlap. You should follow the tutorial with your data and experiment with the settings

**Comment by kuldeep203** [comment]
So what i should try if you can suggest me because i am new in image processing.

**Comment by lukasalexanderweber** [comment]
I would suggest that you 

1. take two pictures with your smartphone with some overlap and stitch them together 
2. make to scans of a document with some overlap and stitch them using `--affine` mode

this way you learn more how stitching works and you can probably apply it on your images if they are suitabel. If you have some time, follow the tutorial with your own images to get a deeper understanding of the stitching proccess 👍
