### ISSUE TITLE
Camera parameters adjusting failed. on two images with slightly different angle

### ISSUE THREAD

**Issue by jeffabc1997** [lukasalexanderweber/stitching#45]
I'm trying to stitch 2 images with similar view.
I've tried change "adjuster" to "no", "affine", "reproj" but didn't get good result. [pic_link](https://github.com/jeffabc1997/pics)
If I use "ray", it will have error.
`stitching.stitching_error.StitchingError: Camera parameters adjusting failed.`
My setting:
```
settings = {"detector": "sift", "confidence_threshold": 0.5, "adjuster": "no"}
stitcher = stitching.Stitcher(**settings)
```
Thanks.

**Comment by lukasalexanderweber** [comment]
The images might be too similar. Maybe a [Affine Stitcher](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/stitcher.py#L249) works better?

**Comment by jeffabc1997** [comment]
Unfortunately, the [created picture](https://github.com/jeffabc1997/pics/blob/main/affine/bin000004_08.jpg) seems to have no transformation.
My code:
```
stitcher = stitching.AffineStitcher()
panorama = stitcher.stitch([img1_path, img2_path])
```

Thanks!

**Comment by lukasalexanderweber** [comment]
your result seems fine to me. What do you expect?

**Comment by jeffabc1997** [comment]
I would like to stitch the [left](https://github.com/jeffabc1997/pics/blob/main/000004_08.jpg) and [right](https://github.com/jeffabc1997/pics/blob/main/000004_08_2.jpg) together, so I hope that the rightmost area (more leaves, car shadow) of the right image can show on the result image.

**Comment by lukasalexanderweber** [comment]
please follow the [tutorial](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md) to find out where the problem occurs
