### ISSUE TITLE
Camera parameters adjusting failed when using homography setting on nearly homography images

### ISSUE THREAD

**Issue by algopert** [lukasalexanderweber/stitching#47]
Thanks for the wonderful repo.

I am trying to stitch about 40 images of room.

Images are overlapping by about 50%. 

But I only can see infinite loop in CameraAdjuster().

The repo is working well with 4–6 images.

I tried to change its parameter to "no" but image flipped and bad quality.

Could you please help me?

Thank you in advance.

**Comment by algopert** [comment]
Hi
Thanks for your reply.

I have a plan to do so.

In order to do that, I am going to 

I'm trying to do it by grouping 6 images together.

**Comment by algopert** [comment]
Can I share my contact info with you?
Am eager to be your friend.
:)

**Comment by lukasalexanderweber** [comment]
you can share it to l.a.weber@outlook.de (usually you find contact infos in  the [setup.cfg](https://github.com/lukasalexanderweber/stitching/blob/main/setup.cfg)) :)

**Comment by lukasalexanderweber** [comment]
Any updates in your Problem?

**Comment by algopert** [comment]
There was bug in subsetter()...
