### ISSUE TITLE
Bug in Largest Interior/Inscribed Rectangle implementation

### ISSUE THREAD

**Issue by algopert** [lukasalexanderweber/stitching#48]
**Traceback (most recent call last):
  File "f:\Yuri_Approach\my_new_approach.py", line 291, in <module>
    lir = cropper.estimate_largest_interior_rectangle(mask)
  File "f:\Yuri_Approach\stitching\cropper.py", line 98, in estimate_largest_interior_rectangle
    raise StitchingError("Invalid Contour. Try without cropping.")
stitching.stitching_error.StitchingError: Invalid Contour. Try without cropping.**

**Comment by algopert** [comment]
![image](https://user-images.githubusercontent.com/96640049/217362665-ab87cebc-42a3-4314-8804-ba542ca929ff.png)

**Comment by lukasalexanderweber** [comment]
This is intentional since you have a black 'island' within your resulting image

**Comment by algopert** [comment]
![image](https://user-images.githubusercontent.com/96640049/230452000-af993b88-9680-47ce-949a-9f17713659c2.png)
**raise StitchingError("Invalid Contour. Try without cropping.")
stitching.stitching_error.StitchingError: Invalid Contour. Try without cropping.**

What's wrong?

**Comment by lukasalexanderweber** [comment]
@algopert good question, it seems fine at first glance.
