### ISSUE TITLE
Bug in subsetter.subset_matches()

### ISSUE THREAD

**Issue by algopert** [lukasalexanderweber/stitching#50]
Hi Lukas

Original confindence matrix is:
![image](https://user-images.githubusercontent.com/96640049/218410739-bc1139c2-d973-46bb-95cb-c5cc323fe43f.png)

indices_to_keep is **[ 1  4  5  6  7  8  9 10 11 16 17 18 20 21 22 24 25 29 30 31 32 33 34 35
 36]**

But the result of **matches = subsetter.subset_matches(matches, indices)**
is
![image](https://user-images.githubusercontent.com/96640049/218411447-532b5208-d764-4a0d-8c6a-dc6808bf140d.png)

What I am interested is pair [1,25] = 1.1
Where'd 1.1 go? :)

Seems that subsetter.subset_matches() has a bug...
I am digging in it.

Please let me know your thought.

Thanks.

**Comment by algopert** [comment]
I am sure it is the main cause to arise the error in camera_adjuster.adjust()

**Comment by lukasalexanderweber** [comment]
Hey, good to know! Can you please share how you solved the Bug?

**Comment by algopert** [comment]
Can I push my code to git?
I recreated the function.
All is working VERY WELL. :)

get_indices_to_delete(), subset_matrix(), delete_index_from_matrix() are not necessary totally.
But in this case, the code can't pass UnitTest.

Please let me know.

**Comment by lukasalexanderweber** [comment]
feel free to open a Pull Request 👍

**Comment by lukasalexanderweber** [comment]
please leave this open until a possible PR is merged.

specify 

closes https://github.com/lukasalexanderweber/stitching/issues/50

in your PR to indicate this issue will automatically be closed if the PR is merged automatically

**Comment by algopert** [comment]
Pushed.
