### ISSUE TITLE
Bug in FeatureMatcher()

### ISSUE THREAD

**Issue by algopert** [lukasalexanderweber/stitching#52]
It seems that each element interfere to each other.
After removing 7th image, I can get correct the result.
![image](https://user-images.githubusercontent.com/96640049/219477400-b430ad27-75f5-456a-8008-4cc4d52c3022.png)

Only after physically removing the 7th image, I had got the correct result. 
If I understand the theory correctly, the matching result should only depend on 2 feature packs. Why is 3rd party intervention having an impact? 
This result doesn't depend on whether I use match-mask or not as well.

**Comment by algopert** [comment]
Ok. It was derived from that I settled range_width to 10.
![image](https://user-images.githubusercontent.com/96640049/219501380-ab8565ff-4c53-4325-af40-806da982ebad.png)

But still not sure why the match cofidence is slightly different.
![image](https://user-images.githubusercontent.com/96640049/219501572-d43661bc-eac5-4d00-afd5-aa8b65f869c3.png)

**Comment by lukasalexanderweber** [comment]
The confidence varies from Run to Run

**Comment by algopert** [comment]
Thanks. I guess because the algo is using RANSAC.

Could you please answer my another question?
![image](https://user-images.githubusercontent.com/96640049/219698640-accb0c51-e801-42d8-8119-dadc6fad041c.png)

First case is to attach 4 images serially.
I have no issue on it.

But in 2nd case, all images have enough confidence to each other.

At this point, do all confidence participate in the camera estimator calculation?
Or are some of the confidences removed to construct a loop-free graph?

Thanks.

**Comment by lukasalexanderweber** [comment]
can you please create a matches graph

`--matches_graph_dot_file matches.txt`

and share the result for your use case?

**Comment by algopert** [comment]
[graph.txt](https://github.com/lukasalexanderweber/stitching/files/10771985/graph.txt)

**Comment by algopert** [comment]
-----  Confidence Matrix---------
[[0.   2.35 0.3  0.57] 
 [2.35 0.   0.52 0.37] 
 [0.3  0.52 0.   1.2 ] 
 [0.57 0.37 1.2  0.  ]]
Matches Image 0 to Image 1: CF 2.35 195
Matches Image 0 to Image 3: CF 0.57 29
Matches Image 1 to Image 2: CF 0.52 27
Matches Image 2 to Image 3: CF 1.2 165
![image](https://user-images.githubusercontent.com/96640049/219803900-7f057e2f-87dc-4fb1-ad70-ca666448a497.png)

**Comment by algopert** [comment]
The case using "BRISK"
```
-----  Confidence Matrix---------
[[0.   2.08 0.84 0.77]
 [2.08 0.   1.22 1.05]
 [0.84 1.22 0.   2.16]
 [0.77 1.05 2.16 0.  ]]
Matches Image 0 to Image 1: CF 2.08 137
Matches Image 0 to Image 2: CF 0.84 18
Matches Image 0 to Image 3: CF 0.77 16
Matches Image 1 to Image 2: CF 1.22 24
Matches Image 1 to Image 3: CF 1.05 20
Matches Image 2 to Image 3: CF 2.16 303
graph matches_graph{
"46_-28_1_-133_41_65.png" -- "47_-14_2_-134_41_65.png"[label="Nm=193, Ni=137, C=2.07891"];
"46_-28_1_-133_41_65.png" -- "70_-30_1_-47_41_65.png"[label="Nm=45, Ni=18, C=0.837209"];  
"46_-28_1_-133_41_65.png" -- "71_-14_0_-46_41_65.png"[label="Nm=43, Ni=16, C=0.76555"];
}
```

**Comment by lukasalexanderweber** [comment]
In this case all Images are alinged relatively to 46_-28_1_-133_41_65.png

**Comment by algopert** [comment]
Is there any way to introduce FLANN matcher?

**Comment by lukasalexanderweber** [comment]
From the [Docs](https://docs.opencv.org/4.7.0/db/d39/classcv_1_1DescriptorMatcher.html) you should be able to include it

**Comment by algopert** [comment]
Thanks.
Tried, but KNN matcher was worse!

Anyway, thanks a lot!

**Comment by algopert** [comment]
Yes, for example

![image](https://user-images.githubusercontent.com/96640049/220037449-c88a410e-c4a0-4f16-9818-311eaa988fb4.png)
![image](https://user-images.githubusercontent.com/96640049/220037575-ba160b0d-67c7-4f4e-ba4a-caa3dfc78849.png)

**Comment by algopert** [comment]
![image](https://user-images.githubusercontent.com/96640049/220038025-b222a429-58a1-4127-9467-6c53fea29c51.png)

**Comment by lukasalexanderweber** [comment]
I think those features are filtered out because of [Lowe's Ratio test](https://stackoverflow.com/questions/51197091/how-does-the-lowes-ratio-test-work) (they are too similar). You can play around with the match_conf parameter to maybe be able to include them.

**Comment by algopert** [comment]
Yes, I tried it as well.
![image](https://user-images.githubusercontent.com/96640049/220039462-98f29446-6024-434d-8de7-5c02500b522a.png)
But it was algo pointless.

**Comment by lukasalexanderweber** [comment]
ok. we would need to dig deeper on if matches are computed and where they are omitted (Ratio Test? RANSAC?).

**Comment by algopert** [comment]
Agreed! :)

**Comment by lukasalexanderweber** [comment]
I'll close this issue, but you can keep me updated here if you make any progress :)

**Comment by algopert** [comment]
Ok, Thanks.

**Comment by algopert** [comment]
Hi Lukas.

Hope you are well.

I faced one issue...

I attempted to stitch only 2 images using a homography.
`matches[1].H` was used as the homography matrix.
But contrary to my expectations, I can't stitch the 2 images properly.

All is from your code.
My snippet are as follow.

```
fileNames = ["5_150_0_-88_41_65.png","6_180_0_-92_41_65.png"]
img_handler = ImageHandler()
img_handler.set_img_names(fileNames)

medium_imgs = list(img_handler.resize_to_final_resolution())
low_imgs = list(img_handler.resize_to_low_resolution(medium_imgs))
final_imgs = list(img_handler.resize_to_final_resolution())
...
i = matches[1].src_img_idx
j = matches[1].dst_img_idx
homoMatrix = matches[1].H

srcImg = medium_imgs[i]
dstImg = medium_imgs[j]


dst = cv.warpPerspective(srcImg,homoMatrix,(dstImg.shape[1] + srcImg.shape[1], srcImg.shape[0]))
dst[0:dstImg.shape[0],0:dstImg.shape[1]] = dstImg
plot_image(dst)

```
Could you please let me know what is my mistakes?

**Comment by algopert** [comment]
![image](https://user-images.githubusercontent.com/96640049/221545621-23506fc4-de9c-47f9-896e-4182ba6b2616.png)

**Comment by lukasalexanderweber** [comment]
Have you make any progress? I'm sadly not that deep into homography matrix to see the issue on the first glance :/

**Comment by algopert** [comment]
I mean I couldn't overlay the 2nd image on the 1st image by using `match[i].H`.
So I just thought `match[i].H` is not homography matrix...
If so, what is `match[i].H`?
