### ISSUE TITLE
Stitching high resolution images

### ISSUE THREAD

**Issue by limchengwei** [lukasalexanderweber/stitching#53]
Hi,

Can we used it to stitch small printed details of high resolution images? How can we go about?

Many thanks.

**Comment by lukasalexanderweber** [comment]
Yeah this is the main reason why I created this repo.

For high resolution images you probably need to increase `low_megapix` (e.g. to 1) and `medium_megapix` (e.g. to 5). 

Set `final_megapix` to something not that high (e.g. also 5) so you don't have to wait that long for a result while experimenting with the settings. If you are satisfied, remove it or set to -1 to get the result with the original image resolution.

To summarize, in my experience it's the easiest to manipulate the image sizes before feature matching using the [image_handler](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/image_handler.py) (for image registration `work_megapix` is used, for composition (exposure correction and seam finding) `low_megapix`)

You can also follow the tutorial till [match features](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md#match-features), where you can analyze if your details are treated as matching features.

**Comment by limchengwei** [comment]
Thank you for your reply. I was thinking could you let us annotate landmarks in our images like those green circles for similar points and stitch them together?

**Comment by Kalo0m** [comment]
> Yeah this is the main reason why I created this repo.
> 
> For high resolution images you probably need to increase `low_megapix` (e.g. to 1) and `medium_megapix` (e.g. to 5).
> 
> Set `final_megapix` to something not that high (e.g. also 5) so you don't have to wait that long for a result while experimenting with the settings. If you are satisfied, remove it or set to -1 to get the result with the original image resolution.
> 
> To summarize, in my experience it's the easiest to manipulate the image sizes before feature matching using the [image_handler](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/image_handler.py) (for image registration `work_megapix` is used, for composition (exposure correction and seam finding) `low_megapix`)
> 
> You can also follow the tutorial till [match features](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md#match-features), where you can analyze if your details are treated as matching features.

what can we do if those features aren't treated ? I've tried to upgrade `nfeatures` but they are all in the same place
<img width="791" alt="image" src="https://user-images.githubusercontent.com/61421713/222451094-0fcb35c0-1ea9-4219-965f-16e69c362c8b.png">

**Comment by lukasalexanderweber** [comment]
@Kalo0m are you and @limchengwei working together on this? Just for my understanding.

**Comment by lukasalexanderweber** [comment]
> I have images that have similar features like many similar circles and lines

Do you have an example?

**Comment by Kalo0m** [comment]
@lukasalexanderweber not at all, I thought my problem was related to high resolution images (from an iphone 13)

**Comment by limchengwei** [comment]
Hi @lukasalexanderweber ,

Unfortunately, my images are classified in my company. They are 2 images with lots of same sized circles of small pixels. However, there are lines which are features to find the overlapping region in the 2 images.

I tried your team's Jupyter script and found it very helpful in stitching large features that have lots of pixels in them.

Here is one of the 9 images:
<img width="208" alt="grid1" src="https://user-images.githubusercontent.com/85741357/222991508-0125b6af-1dc4-42a8-9dfe-b7e0009e3322.png">

Its 9 images stitched:
![output](https://user-images.githubusercontent.com/85741357/222991461-39a7a1ee-02c6-4e82-b4bd-a0ff1827723b.png)

However, I failed to stitch my company's images because of small pixels of similar circles. Hope you can help.

Thank you.

**Comment by limchengwei** [comment]
I think we can have a possible solution to mitigrate the error to extract the features. If there is two images, for the left image, can we select the region of interest ROI of overlapping region with the left part of the right image? Silimar for the right image, can we select the region of interest of overlapping region with the right part of the left image? Then we stitch them using relation.

Thanks.

**Comment by lukasalexanderweber** [comment]
Do you mean a ROI where you can specify where features are searched? Could https://github.com/lukasalexanderweber/stitching/pull/55 help for this?

**Comment by lukasalexanderweber** [comment]
sorry

**Comment by limchengwei** [comment]
@lukasalexanderweber , yes I am trying out. Thank you.

**Comment by limchengwei** [comment]
How can we use
stitch b.jpg c.jpg a.jpg --range_width 1 --confidence_threshold 0
in Juypter Notebook?

**Comment by lukasalexanderweber** [comment]
![image](https://user-images.githubusercontent.com/32765578/223058493-f8afcc6b-b36d-4671-9752-2eb38c7d3c09.png)

-> `matcher = FeatureMatcher(range_width=1)`

![image](https://user-images.githubusercontent.com/32765578/223058962-e552ca43-1acb-4ad1-938d-3f34b74126f9.png)

-> `subsetter = Subsetter(0)`

**Comment by limchengwei** [comment]
Thank you, I set ROI for the left image and for the right image which are the overlapped region. Then merge the 3 images together.

**Comment by lukasalexanderweber** [comment]
so it works as you expect?

**Comment by limchengwei** [comment]
I found that the overlapped region gives a confidence of about 1.4, which is above 1, which is good relationship. The overlapped region is smaller in height compared to the left and right sides of the 2 images. I resized the overlapped region to concatenate with the left and right sides of the 2 images. But does not give a well stitched image. Will update you next day. Thank you for your support.

**Comment by limchengwei** [comment]
I may need to shift the y-axis of the 3 broken pieces and then crop off some part of the extended images. Then concatenate the images into a single output image.
