### ISSUE TITLE
Feature request - improve matches graph

### ISSUE THREAD

**Issue by Kalo0m** [lukasalexanderweber/stitching#54]
Hi guys,

Firstly thank you all for you amazing work. I would like to have your thoughts on a new feature (afaik not available for now). 

I have a list of ten images and I know the order of them, it would be nice to pass this order in order to override confidence_threshold and get the right graph. Of course it would be an option.

Example: I have 3 photos (A, B and C) and I know the exact order (B --> C --> A). instead of letting the package find the order and maybe be wrong (for example by rejecting A of the result graph), I could pass the graph below as an option to bypass the graph generation.

graph matches_graph{
"B" -- "C"
"C" -- "A"
}

Sorry if I'm not clear, I would like to contribute so what do you think ? Do you have any suggestions ?

**Comment by lukasalexanderweber** [comment]
I have good news for you: It's already a feature.

`stitch b.jpg c.jpg a.jpg --range_width 1 --confidence_threshold 0`

should do the trick. See also https://github.com/lukasalexanderweber/stitching/issues/14

**Comment by lukasalexanderweber** [comment]
I admit that it is not well documented, maybe we should include it in the [stitching_tutorial](https://github.com/lukasalexanderweber/stitching_tutorial)

**Comment by Kalo0m** [comment]
Nice! I will take a look thanks a lot

**Comment by Kalo0m** [comment]
you can also explain what's range_width and what is its impact

**Comment by lukasalexanderweber** [comment]
> setting it to 1 [...] force it to only consider adjacent pairs (e.g. pair 1-2 would have a confidence but pair 1-3 would not)

Setting it to 1 basically just means that that it only looks for matches in images directly to its left or right. 2 would mean 2 images left or right...

All based on the order of the images passed into Stitcher.stitch()

**Comment by Kalo0m** [comment]
And another question, (idk if it's the right place) can the generated image be a spherical photo (in order to put it in a 360 visualizer)?

**Comment by lukasalexanderweber** [comment]
at least there is a `spherical` warper

**Comment by phamkhactu** [comment]
> `stitch b.jpg c.jpg a.jpg --range_width 1 --confidence_threshold 0`

Hi @lukasalexanderweber, @Kalo0m 

Suppose that I have 5 images: "A, B, C, D, E"

I know  matches_graph as below:
```
A --> B 
A --> D
B --> C
B --> D
D --> E 
```

As you suggestion I followed, I get error in [tutorial](https://github.com/OpenStitching/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md) ```cv2.error: OpenCV(4.8.0) /io/opencv/modules/stitching/src/seam_finders.cpp:242: error: (-215:Assertion failed) image2.size() == mask2.size() in function 'process' ```. 

I see that, maybe matches_graph is  matches_graph_dot_file in Subset parameters ?:

```
Subsetter(confidence_threshold=1, matches_graph_dot_file=None)
```

I saw  in matches_graph have [label="Nm=68, Ni=19, C=0.669014"].  What is the master if I don't have label, Ni, C parameters? And if I use fastest function ```  panorama = stitcher.stitch(weid_imgs)
``` as you summary, Can I put matches_graph for creating adjacent panorama as I expect?

**Comment by lukasalexanderweber** [comment]
please use the [discussions](https://github.com/OpenStitching/stitching/discussions) for questions
