### ISSUE TITLE
`python -m unittest` is successful , but run `panorama = stitcher.stitch([image1, image2]) ` is failed, error:  numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by Cheng-qi** [lukasalexanderweber/stitching#63]
import stitching

image1 = '/home/cq/stitching/tests/testdata/boat1.jpg'
image2 = '/home/cq/stitching/tests/testdata/boat2.jpg'
stitcher = stitching.Stitcher() # OK
panorama = stitcher.stitch([image1, image2]) #error
![未命名4](https://user-images.githubusercontent.com/41558367/226262719-1d84c288-7955-4137-87c6-6791dd709a86.jpg)
print(panorama)

**Comment by lukasalexanderweber** [comment]
can you run it with `stitcher = stitching.Stitcher(crop=false)` and show the result?

**Comment by Cheng-qi** [comment]
> can you run it with `stitcher = stitching.Stitcher(crop=false)` and show the result?

Thanks, error has solved.  I have other problem: I try to stitch images longitudinally, but I get a misshapen  result image. 
Can this code get a result images with auto height?

**Comment by lukasalexanderweber** [comment]
the default camera correction is horizontal. You can set it to vertical using `wave_correct_kind=vert` (see [camera_wave_corrector](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/camera_wave_corrector.py)

**Comment by Cheng-qi** [comment]
Thanks very much, It's just what I need!
