### ISSUE TITLE
module 'cv2.cv2' has no attribute 'detail_BundleAdjusterRay'

### ISSUE THREAD

**Issue by CheskaAbarro** [lukasalexanderweber/stitching#65]
Hey, 

First of all, thank you for this wonderful source code. It wasreally helpful for me as a beginner. 

I am having a problem with you Stitching Tutorial jupyter notebook. 
In this line 
```
from stitching.image_handler import ImageHandler

img_handler = ImageHandler()
img_handler.set_img_names(weir_imgs)

medium_imgs = list(img_handler.resize_to_medium_resolution())
low_imgs = list(img_handler.resize_to_low_resolution(medium_imgs))
final_imgs = list(img_handler.resize_to_final_resolution())
```

I am havig this error: 
```
AttributeError: module 'cv2.cv2' has no attribute 'detail_BundleAdjusterRay'
```

and I tried searching it but there is no solution that I found on this one. Can you help me solve this? Greatly appreciated.

**Comment by lukasalexanderweber** [comment]
It seems strange that the module is named `cv2.cv2`.

[here](https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer) is stated that you might need to `pip install opencv-contrib-python`.

How did you installed opencv?

**Comment by lukasalexanderweber** [comment]
It seems strange that the module is named `cv2.cv2`.

[here](https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer) is stated that you might need to `pip install opencv-contrib-python`.

How did you installed opencv?

**Comment by lukasalexanderweber** [comment]
It seems strange that the module is named `cv2.cv2`.

[here](https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer) is stated that you might need to `pip install opencv-contrib-python`.

How did you installed opencv?

**Comment by CheskaAbarro** [comment]
I had the following

opencv-python 4.7.0.72
opencv-contrib-python 4.7.0.72
stitching  0.4.0

I tried bunch of times to install different versions of opencv but the error still persist.

**Comment by lukasalexanderweber** [comment]
you could try only installing `stitching`. Pip will figure out the dependencies.

Do other parts of opencv work? Can you e.g. imread a simple image independent of the stitching package?

**Comment by CheskaAbarro** [comment]
I had a stitching 0.4.0 installed already and I tested, cv2.imread() is working. 

The only line of code that I'm having a problem is with the 
```
from stitching.image_handler import ImageHandler
```

**Comment by lukasalexanderweber** [comment]
sorry I don't really get it becaue `detail_BundleAdjusterRay` is not even called in the image handler

**Comment by CheskaAbarro** [comment]
Hello. 

I had successfully executed your code. I downgraded the requirements into the following:
```
opencv-python = 3.4.2.16
opencv-contrib-python = 3.4.2.16
numpy = 1.21.6
stitching 0.4.0
```

Its a different error but somehow this [solution ](https://stackoverflow.com/questions/58922153/opencv-attributeerror-module-cv2-cv2-has-no-attribute-tracker-create )works. 

You have a wonderful work. Thanks again for sharing it.

**Comment by lukasalexanderweber** [comment]
thanks for your feedback! :)

**Comment by nndei** [comment]
Hello, I am having a similar problem on Mac. 

`Import "stitching.image_handler" could not be resolved Pylance(reportMissingImports)`

I have tried uninstalling stitching, opencv-python, opencv-contrib-python, reinstalling only stitching… but nothing.

**Comment by lukasalexanderweber** [comment]
You need to use the new Tutorial Version

**Comment by nndei** [comment]
Thank you!
