### ISSUE TITLE
Stitching horizontally and vertically stacked images

### ISSUE THREAD

**Issue by aurelien-m** [lukasalexanderweber/stitching#71]
I'm trying to create a panorama from images looking like these:

![6](https://user-images.githubusercontent.com/29719028/231778142-c597ba79-098a-4bbd-b154-6a1185cc6dd1.jpg)
![7](https://user-images.githubusercontent.com/29719028/231778144-351bf860-98e6-4d03-ac82-ac240db39e6c.jpg)
![8](https://user-images.githubusercontent.com/29719028/231778148-da7e1791-ed81-404e-b26e-47955977feab.jpg)
![0](https://user-images.githubusercontent.com/29719028/231778152-083929ef-66e7-4206-a1a5-60816308a1ec.jpg)
![1](https://user-images.githubusercontent.com/29719028/231778157-1a884ea0-140a-4ab6-8097-c1ffeee0aea7.jpg)
![2](https://user-images.githubusercontent.com/29719028/231778164-cfd52133-1ff6-41aa-89e5-ee3ae124b529.jpg)
![3](https://user-images.githubusercontent.com/29719028/231778167-b35cdc89-96d3-43ba-bfeb-ee45d4628563.jpg)
![5](https://user-images.githubusercontent.com/29719028/231778131-9a79c422-27d2-4c41-a73b-581cd2018de3.jpg)
![4](https://user-images.githubusercontent.com/29719028/231778172-e22ae70e-0aeb-43a2-90ec-ea80a5b0a5ab.jpg)

However, I'm getting this error:
```python
Traceback (most recent call last):
  File "/home/aurelien/Projects/Alteia/detection-chambres-orange/streetview/download.py", line 132, in <module>
    panorama = stitcher.stitch(image_paths)
  File "/home/aurelien/Projects/Venvs/compviz/lib/python3.10/site-packages/stitching/stitcher.py", line 94, in stitch
    cameras = self.refine_camera_parameters(features, matches, cameras)
  File "/home/aurelien/Projects/Venvs/compviz/lib/python3.10/site-packages/stitching/stitcher.py", line 147, in refine_camera_parameters
    return self.camera_adjuster.adjust(features, matches, cameras)
  File "/home/aurelien/Projects/Venvs/compviz/lib/python3.10/site-packages/stitching/camera_adjuster.py", line 49, in adjust
    raise StitchingError("Camera parameters adjusting failed.")
stitching.stitching_error.StitchingError: Camera parameters adjusting failed.
```

I also tried the first three images, but I'm getting this:

![test](https://user-images.githubusercontent.com/29719028/231780697-47e49058-25aa-46be-8a1b-03c82c7a2807.png)

Are vertically stacked images supported?

**Comment by lukasalexanderweber** [comment]
can you try with `--wave_correct_kind no`?

**Comment by aurelien-m** [comment]
Thanks, it actually helped quite a bit. But now I'm getting something like this:
![pano_0_fov_70_max_180-stitcher](https://user-images.githubusercontent.com/29719028/231894347-cf7c9ad0-690e-4df2-a436-c45cbf580714.jpg)

With OpenCV's stitcher, I'm able to get this result without touching any settings:
![pano_0_fov_70_max_180-cv2](https://user-images.githubusercontent.com/29719028/231894441-e90efb4b-a9da-41da-88be-6ff4b36eb987.jpg)

OpenCV is much slower though! I'm using the code from the tutorial, I'll try to see if I can tweak the settings to get better results (great tutorial by the way)

**Comment by lukasalexanderweber** [comment]
Thanks for the feedback. 

> With OpenCV's stitcher, I'm able to get this result without touching any settings:

This is odd, since I try to be as close to the original stitching pipeline as possible... Please let me know if you have any findings

**Comment by aurelien-m** [comment]
I modified my input images to have better overlapping areas and different levels of zooms and details, which actually helped a lot. I got something pretty robust now with the standard settings.

I looked through the code and it does look similar to OpenCV :) But I really like what you've done, it's much easier to play around with than what's in OpenCV...

Thanks anyways!

**Comment by lukasalexanderweber** [comment]
> it's much easier to play around with than what's in OpenCV...

thanks :) thats why I created this project and I love how many people seems to like the approach

Cheers
