### ISSUE TITLE
Support for translation

### ISSUE THREAD

**Issue by DiTo97** [lukasalexanderweber/stitching#73]
Hi @lukasalexanderweber,

The OpenCV bundle adjuster does not support translation between frames, but only in-place rotation, in the global optimization step.

During my thesis work two years ago I made something similar to your package, wrapping some of OpenCV's stitching module, but not really quite as polished. As I was dealing with frames that at times suffered from quite a severe translation between them, I found OpenCV's results to be somewhat underwhelming. The bundle adjuster works just fine when the translation is small, but gradually starts to fail the larger it gets.

I started looking into other packages that implemented sparse bundle adjustment, as they had support for translation, but did not have the time to implement the Python bindings and ended up using directly in C++.

Have you ever looked into this? Recently, a [package with bindings of Lourakis' sparse bundle adjustment C library](https://pypi.org/project/sba) has been updated after many years for Python 3 compatibility. Would you be interested in trying to add this functionality to your package?

**Comment by lukasalexanderweber** [comment]
Hey @DiTo97,

thanks for reaching out! :)

> Would you be interested in trying to add this functionality to your package?

I am  generally open to new features if they are developed, tested and documented by the person they are of interest to. 

First of all a sample dataset would be nice that shows the issue and that we can use for testing. 



> Have you ever looked into this?

no, I'm not familiar with the concept of bundle adjustment, till now I've just used what's there.

**Comment by DiTo97** [comment]
Hi @lukasalexanderweber,

I will ask if I can share the dataset, as I have not touched it in two years, but I had already isolated the problematic frames when I used it.

I will let you know next week!

**Comment by DiTo97** [comment]
Hi again @lukasalexanderweber,

I asked for permission, but it was denied, and I cannot share the dataset.

In retrospect, I will close the issue because reworking OpenCV stitching module to enable a translation model would have to dig much deeper than just the bundle adjustment stage, as has already been pointed out in [the answer of this post](https://answers.opencv.org/question/12740/stitching-how-to-get-camera-translation-into-bundle-adjustment/).

Regardless, the problem arises only when the (absolute or relative) 6-dimensional camera poses are unknown and the stitching pipeline has to perform auto-registration to estimate them from the acquired frames.

I would probably consider adding a `cameras` arg to the [`stitch`](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/stitcher.py#L87) function of your `Stitcher` wrapper class. In that way, the auto-registration stage could be made optional in the stitching pipeline. What do you think about that?

## Appendix

For future reference, if anyone had to auto-register 6-dimensional camera poses with translation, I would use the [Pixsfm](https://github.com/cvg/pixel-perfect-sfm) package, which uses [COLMAP](https://colmap.github.io/) and [Ceres Solver](http://ceres-solver.org/) for solving bundle adjustment with support for deep features and GPU acceleration.

Once the auto-registration is complete, the composition code from this package will be used.

**Comment by LeeKeyu** [comment]
Hi @DiTo97  I am also working on the situation when camera translation is large. Thank you for your effort and comments above.
> Regardless, the problem arises only when the (absolute or relative) 6-dimensional camera poses are unknown and the stitching pipeline has to perform auto-registration to estimate them from the acquired frames.
> 
> I would probably consider adding a `cameras` arg to the [`stitch`](https://github.com/lukasalexanderweber/stitching/blob/main/stitching/stitcher.py#L87) function of your `Stitcher` wrapper class. In that way, the auto-registration stage could be made optional in the stitching pipeline. What do you think about that?

Do you mean to use known camera poses to replace what BA module outputs? My question is how to modify the warping step, as the rotation warper in OpenCV seems to only take the camera rotations as input and assumes the camera is at the same point.
Thank you in advance!
